### ISSUE TITLE
[1.15.2] Couldn't read item tag list

### ISSUE THREAD

**Issue by realTIMematrix** [Squidsword/Ores-Above-Diamonds#2]
Hi,

I'm using the following:

Minecraft 1.15.2
Forge 31.0.1
OresAboveDiamonds+1.15+v2.0

Logfile:

`28Jan2020 13:51:24.850] [Server-Worker-1/ERROR] [net.minecraft.tags.TagCollection/]: Couldn't read item tag list oresabovediamonds:amethyst_ore from oresabovediamonds:tags/items/amethyst_ore.json in data pack Mod Resources

com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 6 column 3 path $.values[1]
	at net.minecraft.util.JSONUtils.func_188173_a(SourceFile:496) ~[?:?]
	at net.minecraft.util.JSONUtils.func_193839_a(SourceFile:534) ~[?:?]
	at net.minecraft.tags.TagCollection.lambda$reload$3(TagCollection.java:93) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_241]

Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 6 column 3 path $.values[1]
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[gson-2.8.0.jar:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401) ~[gson-2.8.0.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:560) ~[gson-2.8.0.jar:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:730) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:910) ~[gson-2.8.0.jar:?]
	at net.minecraft.util.JSONUtils.func_188173_a(SourceFile:494) ~[?:?]
	... 8 more`

**Comment by Squidsword** [comment]
Hey, courtesy of Sleeeper, the problem has been fixed. There was a typo on one of the files. I will update the mod soon. Thanks for reporting it.

**Comment by realTIMematrix** [comment]
Great! Thank you. Checked the logfile, created a new world and it looks good now :-)
